name: Node.js CI

on: 
  push:
  check_run:
    types: [rerequested, requested_action]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy: #Esto crea 2 ejecuciones del job automáticamente
      matrix:
        node-version: [18, 20]

    steps:
      
      - name: Debug evento  
        run: |
          echo "Evento: ${{ github.event_name }} - Acción: ${{ github.event.action }}"

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: #$ {{ matrix.node-version }} cada ejecución usa una versión distinta
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v4 #Guarda las dependencias descargadas y Evita instalar desde cero cada vez
        with:
          path: ~/.npm #dónde se guarda cache
          #hashFiles(...) → detecta cambios en dependencias
          #runner.os → separa cache por sistema
          #Si package-lock.json cambia → se invalida cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Use my composite action
        uses: ./.github/actions/my-composite-action
        with:
          node-version: '18'

      - run: npm ci #Usa exactamente package-lock.json
      - run: npm test # Llama al script definido en package.json

      # Matrix → ejecuciones múltiples
      # Cache → optimización
      # npm ci → reproducibilidad
      # setup-node → runtime
      #checkout → obligatorio